export const TableData = [
  {
    id: 1,
    name: "Window Asher",
    topic: "Cafe A 200 for Commercial use",
    status: "new",
    createdOn: "4/02/2024 12:00 PM",
  },
  {
    id: 2,
    name: "Josia Love",
    topic: "Upgrading service plan",
    status: "New",
    createdOn: "3/28/2024 7:45 AM",
  },
  {
    id: 3,
    name: "Harrison Cutis",
    topic: "issue with throughput on ExpressoMaster",
    status: "New ",
    createdOn: "3/28/2024 3:30 PM",
  },
  {
    id: 4,
    name: "Jermaine Berrett",
    topic: "New roaster in distribution facility",
    status: "New ",
    createdOn: "3/25/2024 11:05 AM",
  },
  {
    id: 5,
    name: "Gerald Stephens",
    topic: "Concerns on current machines",
    status: "New ",
    createdOn: "3/23/2024 4:50 PM",
  },
  {
    id: 6,
    name: "Halle Griffiths",
    topic: "Expanding business",
    status: "New ",
    createdOn: "3/21/2024 10:20 AM",
  },
  {
    id: 7,
    name: "Rachel Micheal",
    topic: "Addressing Service concerns",
    status: "New ",
    createdOn: "3/19/2024 1:15 PM",
  },
  {
    id: 8,
    name: "Alex Baker",
    topic: "Premium coffee beans",
    status: "New ",
    createdOn: "3/17/2024 8:00 AM",
  },
  {
    id: 9,
    name: "Lilly Pyles",
    topic: "Cafe A 100 bulk rate",
    status: "New ",
    createdOn: "3/13/2024 2:45 PM",
  },
  {
    id: 10,
    name: "Jane Reyes",
    topic: "Improving cost per cup ",
    status: "New ",
    createdOn: "3/10/2024 9:30 PM",
  },
];
