import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "../../src/components/MainHeader";
import { AppProvider } from "@/context/context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dynamic 365",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <AppProvider>
          <MainHeader />
          <div className="pt-[30px] ">{children}</div>
        </AppProvider>
      </body>
    </html>
  );
}
